### PR TITLE
add path give mut access to families

### PR DESCRIPTION
**Pull request by mxyns**

### CODE REVIEW

**Comment by ahassany** [comment]
What's the use case of this function? This is going to make BGP messages mutable which I'm trying to avoid

**Comment by mxyns** [comment]
a collector crafting the response bgp open. we craft another bgp open and clone the capabilities but we need to set all the addpath caps to receive-only
https://github.com/network-analytics/pmacct-gauze/blob/870bb681af252f39ad56dc7daa79bec5eaa204ec/crates/pmacct-gauze-lib/src/capi/bgp/open.rs#L201C1-L227C7
actually i would've liked to make the flags of AddPathAddressFamily too instead of having to make another one to change the receive/send flags

**Comment by mxyns** [comment]
why are you avoiding mutability on the packets ?

**Comment by ahassany** [comment]
Alright, I will avoid doing this one by one making arbitrarily fields mutable and immutable.  Note, when responding with an open message, AS number and BGP ID can change as well. Generally a BGP speaker decides on the content of BGP open message based on it's configurations not the what the other router advertises. The echo BGP open message is a pmacct specific case.  At the moment it's easy to construct a new BGP open, I've implemented something similar at https://github.com/NetGauze/NetGauze/blob/main/crates/bgp-speaker/src/peer.rs#L91

I've to think about more general approach to consume existing packet and produce a new one with modifications. That approach will address some of the concerns at issue #61 .

**Pull request closed without merging**
